<h5>Request</h5>
<div class="tabs-wrapper">
    <ul class="nav classic-tabs tabs-cyan" role="tablist">
        <li class="nav-item">
            <a class="nav-link waves-light active" data-toggle="tab" href="#reqTrainSeat1" role="tab">URL</a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-light" data-toggle="tab" href="#reqTrainSeat2" role="tab">Parameter</a>
        </li>
    </ul>
</div>
<div class="tab-content card">
    <div class="tab-pane fade in active" id="reqTrainSeat1" role="tabpanel">
        <table class="table table-striped">
            <tbody>
            <tr>
                <th>Method</th>
                <td>POST</td>
            </tr>
            <tr>
                <th>URL</th>
                <td>{{ route('api.trains_get_seat') }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="reqTrainSeat2" role="tabpanel">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Parameter</th>
                <th>Wajib</th>
                <th>Keterangan</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>access_token</th>
                <td>YA/TIDAK</td>
                <td>Gunakan akses token yang didapat ketika GET TOKEN. Jika tidak menggunakan parameter ini, maka
                    gunakan "Authorization : Bearer < access_token >" pada header request
                </td>
            </tr>
            <tr>
                <th>client_id</th>
                <td>YA</td>
                <td>client id</td>
            </tr>
            <tr>
                <th>org</th>
                <td>YA</td>
                <td>Kode stasiun keberangkatan</td>
            </tr>
            <tr>
                <th>des</th>
                <td>YA</td>
                <td>Kode stasiun tujuan</td>
            </tr>
            <tr>
                <th>trip</th>
                <td>YA</td>
                <td>R = untuk pulang pergi, O = untuk sekali jalan.</td>
            </tr>
            <tr>
                <th>tgl_dep</th>
                <td>YA</td>
                <td>Tanggal keberangkatan. Format = yyyy-mm-dd.</td>
            </tr>
            <tr>
                <th>tgl_ret</th>
                <td>TIDAK</td>
                <td>Tanggal kembali. Format = yyyy-mm-dd.<strong> Wajib jika trip=R</strong>.</td>
            </tr>
            <tr>
                <th>adt</th>
                <td>YA</td>
                <td>Jumlah penumpang dewasa (numeric). <strong>minimal 1</strong>.</td>
            </tr>
            <tr>
                <th>chd</th>
                <td>YA</td>
                <td>Jumlah penumpang anak (numeric). <strong>WAJIB 0</strong>.</td>
            </tr>
            <tr>
                <th>inf</th>
                <td>YA</td>
                <td>Jumlah penumpang bayi (numeric). <strong>minimal 0</strong>.</td>
            </tr>
            <tr>
                <th>selectedIDdep</th>
                <td>YA</td>
                <td>selectedIDdep yang di dapat ketika get schedule.</td>
            </tr>
            </tbody>
        </table>
    </div>
</div><h5>Response</h5>
<div class="tabs-wrapper">
    <ul class="nav classic-tabs tabs-cyan" role="tablist">
        <li class="nav-item">
            <a class="nav-link waves-light active" data-toggle="tab" href="#resTrainSeat1" role="tab">Repsonse Berhasil</a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-light" data-toggle="tab" href="#resTrainSeat2" role="tab">Response Gagal</a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-light" data-toggle="tab" href="#resTrainSeat3" role="tab">Penjelasan</a>
        </li>
    </ul>
</div>
<div class="tab-content card">
    <div class="tab-pane fade in active" id="resTrainSeat1" role="tabpanel">
            <pre class="code-toolbar" style="height: 500px">
                <code class="language-markup">
{
  "status": {
    "code": 200,
    "confirm": "success",
    "message": [
      "Success get seat"
    ]
  },
  "details": {
    "queries": {
      "trip": "O",
      "org": "BD",
      "des": "GMR",
      "tgl_dep": "2017-06-12",
      "adt": "1",
      "chd": "0",
      "inf": "0",
      "selectedIDdep": "1481944"
    },
    "seat": {
      "departure": {
        "TrainNo": "37F",
        "SubClass": "A",
        "seat_map": [
          {
            "kode_wagon": "EKO_AC",
            "no_wagon": "1",
            "jml_row": "21",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "C",
                "C",
                "1"
              ],
              [
                "1",
                "D",
                "C",
                "1"
              ],
              [
                "2",
                "A",
                "C",
                "1"
              ],
              [
                "2",
                "B",
                "C",
                "1"
              ],
              [
                "2",
                "C",
                "C",
                "1"
              ],
              [
                "2",
                "D",
                "C",
                "1"
              ],
              [
                "3",
                "A",
                "C",
                "1"
              ],
              [
                "3",
                "B",
                "C",
                "1"
              ],
              [
                "3",
                "C",
                "C",
                "1"
              ],
              [
                "3",
                "D",
                "C",
                "1"
              ],
              [
                "4",
                "A",
                "C",
                "1"
              ],
              [
                "4",
                "B",
                "C",
                "1"
              ],
              [
                "4",
                "C",
                "C",
                "1"
              ],
              [
                "4",
                "D",
                "C",
                "1"
              ],
              [
                "5",
                "A",
                "C",
                "1"
              ],
              [
                "5",
                "B",
                "C",
                "1"
              ],
              [
                "5",
                "C",
                "C",
                "1"
              ],
              [
                "5",
                "D",
                "C",
                "1"
              ],
              [
                "6",
                "A",
                "C",
                "1"
              ],
              [
                "6",
                "B",
                "C",
                "1"
              ],
              [
                "6",
                "C",
                "C",
                "1"
              ],
              [
                "6",
                "D",
                "C",
                "1"
              ],
              [
                "7",
                "A",
                "C",
                "1"
              ],
              [
                "7",
                "B",
                "C",
                "1"
              ],
              [
                "7",
                "C",
                "C",
                "1"
              ],
              [
                "7",
                "D",
                "C",
                "1"
              ],
              [
                "8",
                "A",
                "C",
                "1"
              ],
              [
                "8",
                "B",
                "C",
                "1"
              ],
              [
                "8",
                "C",
                "C",
                "1"
              ],
              [
                "8",
                "D",
                "C",
                "1"
              ],
              [
                "9",
                "A",
                "C",
                "1"
              ],
              [
                "9",
                "B",
                "C",
                "1"
              ],
              [
                "9",
                "C",
                "C",
                "1"
              ],
              [
                "9",
                "D",
                "C",
                "1"
              ],
              [
                "10",
                "A",
                "C",
                "1"
              ],
              [
                "10",
                "B",
                "C",
                "1"
              ],
              [
                "10",
                "C",
                "C",
                "1"
              ],
              [
                "10",
                "D",
                "C",
                "1"
              ],
              [
                "11",
                "A",
                "C",
                "1"
              ],
              [
                "11",
                "B",
                "C",
                "1"
              ],
              [
                "11",
                "C",
                "C",
                "1"
              ],
              [
                "11",
                "D",
                "C",
                "1"
              ],
              [
                "12",
                "A",
                "C",
                "1"
              ],
              [
                "12",
                "B",
                "C",
                "1"
              ],
              [
                "12",
                "C",
                "C",
                "1"
              ],
              [
                "12",
                "D",
                "C",
                "1"
              ],
              [
                "13",
                "A",
                "C",
                "1"
              ],
              [
                "13",
                "B",
                "C",
                "1"
              ],
              [
                "13",
                "C",
                "C",
                "1"
              ],
              [
                "13",
                "D",
                "C",
                "1"
              ],
              [
                "14",
                "A",
                "C",
                "1"
              ],
              [
                "14",
                "B",
                "C",
                "1"
              ],
              [
                "14",
                "C",
                "C",
                "1"
              ],
              [
                "14",
                "D",
                "C",
                "1"
              ],
              [
                "15",
                "A",
                "C",
                "1"
              ],
              [
                "15",
                "B",
                "C",
                "1"
              ],
              [
                "15",
                "C",
                "C",
                "1"
              ],
              [
                "15",
                "D",
                "C",
                "1"
              ],
              [
                "16",
                "A",
                "C",
                "1"
              ],
              [
                "16",
                "B",
                "C",
                "1"
              ],
              [
                "16",
                "C",
                "C",
                "1"
              ],
              [
                "16",
                "D",
                "C",
                "1"
              ],
              [
                "17",
                "A",
                "C",
                "1"
              ],
              [
                "17",
                "B",
                "C",
                "1"
              ],
              [
                "17",
                "C",
                "C",
                "1"
              ],
              [
                "17",
                "D",
                "C",
                "1"
              ],
              [
                "18",
                "A",
                "C",
                "1"
              ],
              [
                "18",
                "B",
                "C",
                "1"
              ],
              [
                "18",
                "C",
                "C",
                "1"
              ],
              [
                "18",
                "D",
                "C",
                "1"
              ],
              [
                "19",
                "A",
                "C",
                "1"
              ],
              [
                "19",
                "B",
                "C",
                "1"
              ],
              [
                "19",
                "C",
                "C",
                "1"
              ],
              [
                "19",
                "D",
                "C",
                "1"
              ],
              [
                "20",
                "A",
                "C",
                "1"
              ],
              [
                "20",
                "B",
                "C",
                "1"
              ],
              [
                "20",
                "C",
                "C",
                "1"
              ],
              [
                "20",
                "D",
                "C",
                "1"
              ],
              [
                "21",
                "A",
                "C",
                "1"
              ],
              [
                "21",
                "B",
                "C",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKO_AC",
            "no_wagon": "2",
            "jml_row": "21",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "C",
                "F",
                "1"
              ],
              [
                "1",
                "D",
                "F",
                "1"
              ],
              [
                "2",
                "A",
                "C",
                "1"
              ],
              [
                "2",
                "B",
                "C",
                "1"
              ],
              [
                "2",
                "C",
                "C",
                "1"
              ],
              [
                "2",
                "D",
                "C",
                "1"
              ],
              [
                "3",
                "A",
                "C",
                "1"
              ],
              [
                "3",
                "B",
                "C",
                "1"
              ],
              [
                "3",
                "C",
                "C",
                "1"
              ],
              [
                "3",
                "D",
                "C",
                "1"
              ],
              [
                "4",
                "A",
                "C",
                "1"
              ],
              [
                "4",
                "B",
                "C",
                "1"
              ],
              [
                "4",
                "C",
                "C",
                "1"
              ],
              [
                "4",
                "D",
                "C",
                "1"
              ],
              [
                "5",
                "A",
                "C",
                "1"
              ],
              [
                "5",
                "B",
                "C",
                "1"
              ],
              [
                "5",
                "C",
                "C",
                "1"
              ],
              [
                "5",
                "D",
                "C",
                "1"
              ],
              [
                "6",
                "A",
                "C",
                "1"
              ],
              [
                "6",
                "B",
                "C",
                "1"
              ],
              [
                "6",
                "C",
                "C",
                "1"
              ],
              [
                "6",
                "D",
                "C",
                "1"
              ],
              [
                "7",
                "A",
                "C",
                "1"
              ],
              [
                "7",
                "B",
                "C",
                "1"
              ],
              [
                "7",
                "C",
                "C",
                "1"
              ],
              [
                "7",
                "D",
                "C",
                "1"
              ],
              [
                "8",
                "A",
                "C",
                "1"
              ],
              [
                "8",
                "B",
                "C",
                "1"
              ],
              [
                "8",
                "C",
                "C",
                "1"
              ],
              [
                "8",
                "D",
                "C",
                "1"
              ],
              [
                "9",
                "A",
                "C",
                "1"
              ],
              [
                "9",
                "B",
                "C",
                "1"
              ],
              [
                "9",
                "C",
                "C",
                "1"
              ],
              [
                "9",
                "D",
                "C",
                "1"
              ],
              [
                "10",
                "A",
                "C",
                "1"
              ],
              [
                "10",
                "B",
                "C",
                "1"
              ],
              [
                "10",
                "C",
                "C",
                "1"
              ],
              [
                "10",
                "D",
                "C",
                "1"
              ],
              [
                "11",
                "A",
                "C",
                "1"
              ],
              [
                "11",
                "B",
                "C",
                "1"
              ],
              [
                "11",
                "C",
                "C",
                "1"
              ],
              [
                "11",
                "D",
                "C",
                "1"
              ],
              [
                "12",
                "A",
                "C",
                "1"
              ],
              [
                "12",
                "B",
                "C",
                "1"
              ],
              [
                "12",
                "C",
                "C",
                "1"
              ],
              [
                "12",
                "D",
                "C",
                "1"
              ],
              [
                "13",
                "A",
                "C",
                "1"
              ],
              [
                "13",
                "B",
                "C",
                "1"
              ],
              [
                "13",
                "C",
                "C",
                "1"
              ],
              [
                "13",
                "D",
                "C",
                "1"
              ],
              [
                "14",
                "A",
                "C",
                "1"
              ],
              [
                "14",
                "B",
                "C",
                "1"
              ],
              [
                "14",
                "C",
                "C",
                "1"
              ],
              [
                "14",
                "D",
                "C",
                "1"
              ],
              [
                "15",
                "A",
                "C",
                "1"
              ],
              [
                "15",
                "B",
                "C",
                "1"
              ],
              [
                "15",
                "C",
                "C",
                "1"
              ],
              [
                "15",
                "D",
                "C",
                "1"
              ],
              [
                "16",
                "A",
                "C",
                "1"
              ],
              [
                "16",
                "B",
                "C",
                "1"
              ],
              [
                "16",
                "C",
                "C",
                "1"
              ],
              [
                "16",
                "D",
                "C",
                "1"
              ],
              [
                "17",
                "A",
                "C",
                "1"
              ],
              [
                "17",
                "B",
                "C",
                "1"
              ],
              [
                "17",
                "C",
                "C",
                "1"
              ],
              [
                "17",
                "D",
                "C",
                "1"
              ],
              [
                "18",
                "A",
                "C",
                "1"
              ],
              [
                "18",
                "B",
                "C",
                "1"
              ],
              [
                "18",
                "C",
                "C",
                "1"
              ],
              [
                "18",
                "D",
                "C",
                "1"
              ],
              [
                "19",
                "A",
                "C",
                "1"
              ],
              [
                "19",
                "B",
                "C",
                "1"
              ],
              [
                "19",
                "C",
                "C",
                "1"
              ],
              [
                "19",
                "D",
                "C",
                "1"
              ],
              [
                "20",
                "A",
                "C",
                "1"
              ],
              [
                "20",
                "B",
                "C",
                "1"
              ],
              [
                "20",
                "C",
                "C",
                "1"
              ],
              [
                "20",
                "D",
                "C",
                "1"
              ],
              [
                "21",
                "A",
                "F",
                "1"
              ],
              [
                "21",
                "B",
                "F",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKO_AC",
            "no_wagon": "3",
            "jml_row": "21",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "C",
                "C",
                "1"
              ],
              [
                "1",
                "D",
                "C",
                "1"
              ],
              [
                "2",
                "A",
                "C",
                "1"
              ],
              [
                "2",
                "B",
                "C",
                "1"
              ],
              [
                "2",
                "C",
                "C",
                "1"
              ],
              [
                "2",
                "D",
                "C",
                "1"
              ],
              [
                "3",
                "A",
                "C",
                "1"
              ],
              [
                "3",
                "B",
                "C",
                "1"
              ],
              [
                "3",
                "C",
                "C",
                "1"
              ],
              [
                "3",
                "D",
                "C",
                "1"
              ],
              [
                "4",
                "A",
                "C",
                "1"
              ],
              [
                "4",
                "B",
                "C",
                "1"
              ],
              [
                "4",
                "C",
                "C",
                "1"
              ],
              [
                "4",
                "D",
                "C",
                "1"
              ],
              [
                "5",
                "A",
                "C",
                "1"
              ],
              [
                "5",
                "B",
                "C",
                "1"
              ],
              [
                "5",
                "C",
                "C",
                "1"
              ],
              [
                "5",
                "D",
                "C",
                "1"
              ],
              [
                "6",
                "A",
                "C",
                "1"
              ],
              [
                "6",
                "B",
                "C",
                "1"
              ],
              [
                "6",
                "C",
                "C",
                "1"
              ],
              [
                "6",
                "D",
                "C",
                "1"
              ],
              [
                "7",
                "A",
                "C",
                "1"
              ],
              [
                "7",
                "B",
                "C",
                "1"
              ],
              [
                "7",
                "C",
                "C",
                "1"
              ],
              [
                "7",
                "D",
                "C",
                "1"
              ],
              [
                "8",
                "A",
                "C",
                "1"
              ],
              [
                "8",
                "B",
                "C",
                "1"
              ],
              [
                "8",
                "C",
                "C",
                "1"
              ],
              [
                "8",
                "D",
                "C",
                "1"
              ],
              [
                "9",
                "A",
                "C",
                "1"
              ],
              [
                "9",
                "B",
                "C",
                "1"
              ],
              [
                "9",
                "C",
                "C",
                "1"
              ],
              [
                "9",
                "D",
                "C",
                "1"
              ],
              [
                "10",
                "A",
                "C",
                "1"
              ],
              [
                "10",
                "B",
                "C",
                "1"
              ],
              [
                "10",
                "C",
                "C",
                "1"
              ],
              [
                "10",
                "D",
                "C",
                "1"
              ],
              [
                "11",
                "A",
                "C",
                "1"
              ],
              [
                "11",
                "B",
                "C",
                "1"
              ],
              [
                "11",
                "C",
                "C",
                "1"
              ],
              [
                "11",
                "D",
                "C",
                "1"
              ],
              [
                "12",
                "A",
                "C",
                "1"
              ],
              [
                "12",
                "B",
                "C",
                "1"
              ],
              [
                "12",
                "C",
                "C",
                "1"
              ],
              [
                "12",
                "D",
                "C",
                "1"
              ],
              [
                "13",
                "A",
                "C",
                "1"
              ],
              [
                "13",
                "B",
                "C",
                "1"
              ],
              [
                "13",
                "C",
                "C",
                "1"
              ],
              [
                "13",
                "D",
                "C",
                "1"
              ],
              [
                "14",
                "A",
                "C",
                "1"
              ],
              [
                "14",
                "B",
                "C",
                "1"
              ],
              [
                "14",
                "C",
                "C",
                "1"
              ],
              [
                "14",
                "D",
                "C",
                "1"
              ],
              [
                "15",
                "A",
                "C",
                "1"
              ],
              [
                "15",
                "B",
                "C",
                "1"
              ],
              [
                "15",
                "C",
                "C",
                "1"
              ],
              [
                "15",
                "D",
                "C",
                "1"
              ],
              [
                "16",
                "A",
                "C",
                "1"
              ],
              [
                "16",
                "B",
                "C",
                "1"
              ],
              [
                "16",
                "C",
                "C",
                "1"
              ],
              [
                "16",
                "D",
                "C",
                "1"
              ],
              [
                "17",
                "A",
                "C",
                "1"
              ],
              [
                "17",
                "B",
                "C",
                "1"
              ],
              [
                "17",
                "C",
                "C",
                "1"
              ],
              [
                "17",
                "D",
                "C",
                "1"
              ],
              [
                "18",
                "A",
                "C",
                "1"
              ],
              [
                "18",
                "B",
                "C",
                "1"
              ],
              [
                "18",
                "C",
                "C",
                "1"
              ],
              [
                "18",
                "D",
                "C",
                "1"
              ],
              [
                "19",
                "A",
                "C",
                "1"
              ],
              [
                "19",
                "B",
                "C",
                "1"
              ],
              [
                "19",
                "C",
                "C",
                "1"
              ],
              [
                "19",
                "D",
                "C",
                "1"
              ],
              [
                "20",
                "A",
                "C",
                "1"
              ],
              [
                "20",
                "B",
                "C",
                "1"
              ],
              [
                "20",
                "C",
                "C",
                "1"
              ],
              [
                "20",
                "D",
                "C",
                "1"
              ],
              [
                "21",
                "A",
                "C",
                "1"
              ],
              [
                "21",
                "B",
                "C",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKO_AC",
            "no_wagon": "4",
            "jml_row": "21",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "C",
                "C",
                "1"
              ],
              [
                "1",
                "D",
                "C",
                "1"
              ],
              [
                "2",
                "A",
                "C",
                "1"
              ],
              [
                "2",
                "B",
                "C",
                "1"
              ],
              [
                "2",
                "C",
                "C",
                "1"
              ],
              [
                "2",
                "D",
                "C",
                "1"
              ],
              [
                "3",
                "A",
                "C",
                "1"
              ],
              [
                "3",
                "B",
                "C",
                "1"
              ],
              [
                "3",
                "C",
                "C",
                "1"
              ],
              [
                "3",
                "D",
                "C",
                "1"
              ],
              [
                "4",
                "A",
                "C",
                "1"
              ],
              [
                "4",
                "B",
                "C",
                "1"
              ],
              [
                "4",
                "C",
                "C",
                "1"
              ],
              [
                "4",
                "D",
                "C",
                "1"
              ],
              [
                "5",
                "A",
                "C",
                "1"
              ],
              [
                "5",
                "B",
                "C",
                "1"
              ],
              [
                "5",
                "C",
                "C",
                "1"
              ],
              [
                "5",
                "D",
                "C",
                "1"
              ],
              [
                "6",
                "A",
                "C",
                "1"
              ],
              [
                "6",
                "B",
                "C",
                "1"
              ],
              [
                "6",
                "C",
                "C",
                "1"
              ],
              [
                "6",
                "D",
                "C",
                "1"
              ],
              [
                "7",
                "A",
                "C",
                "1"
              ],
              [
                "7",
                "B",
                "C",
                "1"
              ],
              [
                "7",
                "C",
                "C",
                "1"
              ],
              [
                "7",
                "D",
                "C",
                "1"
              ],
              [
                "8",
                "A",
                "C",
                "1"
              ],
              [
                "8",
                "B",
                "C",
                "1"
              ],
              [
                "8",
                "C",
                "C",
                "1"
              ],
              [
                "8",
                "D",
                "C",
                "1"
              ],
              [
                "9",
                "A",
                "C",
                "1"
              ],
              [
                "9",
                "B",
                "C",
                "1"
              ],
              [
                "9",
                "C",
                "C",
                "1"
              ],
              [
                "9",
                "D",
                "C",
                "1"
              ],
              [
                "10",
                "A",
                "C",
                "1"
              ],
              [
                "10",
                "B",
                "C",
                "1"
              ],
              [
                "10",
                "C",
                "C",
                "1"
              ],
              [
                "10",
                "D",
                "C",
                "1"
              ],
              [
                "11",
                "A",
                "C",
                "1"
              ],
              [
                "11",
                "B",
                "C",
                "1"
              ],
              [
                "11",
                "C",
                "C",
                "1"
              ],
              [
                "11",
                "D",
                "C",
                "1"
              ],
              [
                "12",
                "A",
                "C",
                "1"
              ],
              [
                "12",
                "B",
                "C",
                "1"
              ],
              [
                "12",
                "C",
                "C",
                "1"
              ],
              [
                "12",
                "D",
                "C",
                "1"
              ],
              [
                "13",
                "A",
                "C",
                "1"
              ],
              [
                "13",
                "B",
                "C",
                "1"
              ],
              [
                "13",
                "C",
                "C",
                "1"
              ],
              [
                "13",
                "D",
                "C",
                "1"
              ],
              [
                "14",
                "A",
                "C",
                "1"
              ],
              [
                "14",
                "B",
                "C",
                "1"
              ],
              [
                "14",
                "C",
                "C",
                "1"
              ],
              [
                "14",
                "D",
                "C",
                "1"
              ],
              [
                "15",
                "A",
                "C",
                "1"
              ],
              [
                "15",
                "B",
                "C",
                "1"
              ],
              [
                "15",
                "C",
                "C",
                "1"
              ],
              [
                "15",
                "D",
                "C",
                "1"
              ],
              [
                "16",
                "A",
                "C",
                "1"
              ],
              [
                "16",
                "B",
                "C",
                "1"
              ],
              [
                "16",
                "C",
                "C",
                "1"
              ],
              [
                "16",
                "D",
                "C",
                "1"
              ],
              [
                "17",
                "A",
                "C",
                "1"
              ],
              [
                "17",
                "B",
                "C",
                "1"
              ],
              [
                "17",
                "C",
                "C",
                "1"
              ],
              [
                "17",
                "D",
                "C",
                "1"
              ],
              [
                "18",
                "A",
                "C",
                "1"
              ],
              [
                "18",
                "B",
                "C",
                "1"
              ],
              [
                "18",
                "C",
                "C",
                "1"
              ],
              [
                "18",
                "D",
                "C",
                "1"
              ],
              [
                "19",
                "A",
                "C",
                "1"
              ],
              [
                "19",
                "B",
                "C",
                "1"
              ],
              [
                "19",
                "C",
                "C",
                "1"
              ],
              [
                "19",
                "D",
                "C",
                "1"
              ],
              [
                "20",
                "A",
                "C",
                "1"
              ],
              [
                "20",
                "B",
                "C",
                "1"
              ],
              [
                "20",
                "C",
                "C",
                "1"
              ],
              [
                "20",
                "D",
                "C",
                "1"
              ],
              [
                "21",
                "A",
                "C",
                "1"
              ],
              [
                "21",
                "B",
                "C",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKS",
            "no_wagon": "1",
            "jml_row": "13",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "A",
                "A",
                "1"
              ],
              [
                "1",
                "B",
                "A",
                "1"
              ],
              [
                "1",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "A",
                "A",
                "1"
              ],
              [
                "2",
                "B",
                "A",
                "1"
              ],
              [
                "2",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "D",
                "A",
                "1"
              ],
              [
                "3",
                "A",
                "A",
                "1"
              ],
              [
                "3",
                "B",
                "A",
                "0"
              ],
              [
                "3",
                "C",
                "A",
                "1"
              ],
              [
                "3",
                "D",
                "A",
                "1"
              ],
              [
                "4",
                "A",
                "A",
                "1"
              ],
              [
                "4",
                "B",
                "A",
                "1"
              ],
              [
                "4",
                "C",
                "A",
                "1"
              ],
              [
                "4",
                "D",
                "A",
                "1"
              ],
              [
                "5",
                "A",
                "A",
                "1"
              ],
              [
                "5",
                "B",
                "A",
                "0"
              ],
              [
                "5",
                "C",
                "A",
                "1"
              ],
              [
                "5",
                "D",
                "A",
                "1"
              ],
              [
                "6",
                "A",
                "A",
                "1"
              ],
              [
                "6",
                "B",
                "A",
                "1"
              ],
              [
                "6",
                "C",
                "A",
                "0"
              ],
              [
                "6",
                "D",
                "A",
                "1"
              ],
              [
                "7",
                "A",
                "A",
                "1"
              ],
              [
                "7",
                "B",
                "A",
                "1"
              ],
              [
                "7",
                "C",
                "A",
                "0"
              ],
              [
                "7",
                "D",
                "A",
                "1"
              ],
              [
                "8",
                "A",
                "A",
                "1"
              ],
              [
                "8",
                "B",
                "A",
                "1"
              ],
              [
                "8",
                "C",
                "A",
                "0"
              ],
              [
                "8",
                "D",
                "A",
                "1"
              ],
              [
                "9",
                "A",
                "A",
                "1"
              ],
              [
                "9",
                "B",
                "A",
                "1"
              ],
              [
                "9",
                "C",
                "A",
                "0"
              ],
              [
                "9",
                "D",
                "A",
                "1"
              ],
              [
                "10",
                "A",
                "A",
                "1"
              ],
              [
                "10",
                "B",
                "A",
                "0"
              ],
              [
                "10",
                "C",
                "A",
                "1"
              ],
              [
                "10",
                "D",
                "A",
                "1"
              ],
              [
                "11",
                "A",
                "A",
                "1"
              ],
              [
                "11",
                "B",
                "A",
                "0"
              ],
              [
                "11",
                "C",
                "A",
                "1"
              ],
              [
                "11",
                "D",
                "A",
                "1"
              ],
              [
                "12",
                "A",
                "A",
                "1"
              ],
              [
                "12",
                "B",
                "A",
                "0"
              ],
              [
                "12",
                "C",
                "A",
                "1"
              ],
              [
                "12",
                "D",
                "A",
                "1"
              ],
              [
                "13",
                "B",
                "A",
                "1"
              ],
              [
                "13",
                "C",
                "A",
                "0"
              ],
              [
                "13",
                "D",
                "A",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKS",
            "no_wagon": "2",
            "jml_row": "13",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "A",
                "A",
                "1"
              ],
              [
                "1",
                "B",
                "A",
                "0"
              ],
              [
                "1",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "A",
                "A",
                "1"
              ],
              [
                "2",
                "B",
                "A",
                "0"
              ],
              [
                "2",
                "C",
                "A",
                "0"
              ],
              [
                "2",
                "D",
                "A",
                "1"
              ],
              [
                "3",
                "A",
                "D",
                "1"
              ],
              [
                "3",
                "B",
                "D",
                "1"
              ],
              [
                "3",
                "C",
                "A",
                "0"
              ],
              [
                "3",
                "D",
                "A",
                "1"
              ],
              [
                "4",
                "A",
                "A",
                "1"
              ],
              [
                "4",
                "B",
                "A",
                "0"
              ],
              [
                "4",
                "C",
                "A",
                "0"
              ],
              [
                "4",
                "D",
                "A",
                "1"
              ],
              [
                "5",
                "A",
                "A",
                "1"
              ],
              [
                "5",
                "B",
                "A",
                "1"
              ],
              [
                "5",
                "C",
                "A",
                "0"
              ],
              [
                "5",
                "D",
                "A",
                "1"
              ],
              [
                "6",
                "A",
                "A",
                "1"
              ],
              [
                "6",
                "B",
                "A",
                "0"
              ],
              [
                "6",
                "C",
                "A",
                "1"
              ],
              [
                "6",
                "D",
                "A",
                "1"
              ],
              [
                "7",
                "A",
                "A",
                "1"
              ],
              [
                "7",
                "B",
                "A",
                "0"
              ],
              [
                "7",
                "C",
                "A",
                "0"
              ],
              [
                "7",
                "D",
                "A",
                "1"
              ],
              [
                "8",
                "A",
                "A",
                "1"
              ],
              [
                "8",
                "B",
                "A",
                "1"
              ],
              [
                "8",
                "C",
                "A",
                "0"
              ],
              [
                "8",
                "D",
                "A",
                "1"
              ],
              [
                "9",
                "A",
                "A",
                "1"
              ],
              [
                "9",
                "B",
                "A",
                "1"
              ],
              [
                "9",
                "C",
                "A",
                "0"
              ],
              [
                "9",
                "D",
                "A",
                "1"
              ],
              [
                "10",
                "A",
                "A",
                "1"
              ],
              [
                "10",
                "B",
                "A",
                "0"
              ],
              [
                "10",
                "C",
                "A",
                "0"
              ],
              [
                "10",
                "D",
                "A",
                "1"
              ],
              [
                "11",
                "A",
                "A",
                "1"
              ],
              [
                "11",
                "B",
                "A",
                "0"
              ],
              [
                "11",
                "C",
                "D",
                "1"
              ],
              [
                "11",
                "D",
                "D",
                "1"
              ],
              [
                "12",
                "A",
                "A",
                "1"
              ],
              [
                "12",
                "B",
                "A",
                "0"
              ],
              [
                "12",
                "C",
                "A",
                "0"
              ],
              [
                "12",
                "D",
                "A",
                "1"
              ],
              [
                "13",
                "B",
                "A",
                "1"
              ],
              [
                "13",
                "C",
                "A",
                "0"
              ],
              [
                "13",
                "D",
                "A",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKS",
            "no_wagon": "3",
            "jml_row": "13",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "A",
                "A",
                "1"
              ],
              [
                "1",
                "B",
                "A",
                "1"
              ],
              [
                "1",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "A",
                "A",
                "1"
              ],
              [
                "2",
                "B",
                "A",
                "0"
              ],
              [
                "2",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "D",
                "A",
                "1"
              ],
              [
                "3",
                "A",
                "A",
                "1"
              ],
              [
                "3",
                "B",
                "A",
                "0"
              ],
              [
                "3",
                "C",
                "A",
                "0"
              ],
              [
                "3",
                "D",
                "A",
                "1"
              ],
              [
                "4",
                "A",
                "A",
                "1"
              ],
              [
                "4",
                "B",
                "A",
                "0"
              ],
              [
                "4",
                "C",
                "A",
                "0"
              ],
              [
                "4",
                "D",
                "A",
                "1"
              ],
              [
                "5",
                "A",
                "A",
                "1"
              ],
              [
                "5",
                "B",
                "A",
                "1"
              ],
              [
                "5",
                "C",
                "A",
                "0"
              ],
              [
                "5",
                "D",
                "A",
                "1"
              ],
              [
                "6",
                "A",
                "A",
                "1"
              ],
              [
                "6",
                "B",
                "A",
                "1"
              ],
              [
                "6",
                "C",
                "A",
                "0"
              ],
              [
                "6",
                "D",
                "A",
                "1"
              ],
              [
                "7",
                "A",
                "A",
                "1"
              ],
              [
                "7",
                "B",
                "A",
                "0"
              ],
              [
                "7",
                "C",
                "A",
                "0"
              ],
              [
                "7",
                "D",
                "A",
                "1"
              ],
              [
                "8",
                "A",
                "A",
                "1"
              ],
              [
                "8",
                "B",
                "A",
                "0"
              ],
              [
                "8",
                "C",
                "A",
                "0"
              ],
              [
                "8",
                "D",
                "A",
                "1"
              ],
              [
                "9",
                "A",
                "A",
                "1"
              ],
              [
                "9",
                "B",
                "A",
                "0"
              ],
              [
                "9",
                "C",
                "A",
                "0"
              ],
              [
                "9",
                "D",
                "A",
                "1"
              ],
              [
                "10",
                "A",
                "A",
                "1"
              ],
              [
                "10",
                "B",
                "A",
                "0"
              ],
              [
                "10",
                "C",
                "A",
                "0"
              ],
              [
                "10",
                "D",
                "A",
                "1"
              ],
              [
                "11",
                "A",
                "A",
                "1"
              ],
              [
                "11",
                "B",
                "A",
                "0"
              ],
              [
                "11",
                "C",
                "A",
                "0"
              ],
              [
                "11",
                "D",
                "A",
                "1"
              ],
              [
                "12",
                "A",
                "A",
                "1"
              ],
              [
                "12",
                "B",
                "A",
                "0"
              ],
              [
                "12",
                "C",
                "A",
                "0"
              ],
              [
                "12",
                "D",
                "A",
                "0"
              ],
              [
                "13",
                "B",
                "A",
                "1"
              ],
              [
                "13",
                "C",
                "A",
                "0"
              ],
              [
                "13",
                "D",
                "A",
                "1"
              ]
            ]
          },
          {
            "kode_wagon": "EKS",
            "no_wagon": "4",
            "jml_row": "13",
            "jml_col": "4",
            "avl": [
              [
                "1",
                "A",
                "A",
                "0"
              ],
              [
                "1",
                "B",
                "A",
                "0"
              ],
              [
                "1",
                "C",
                "A",
                "1"
              ],
              [
                "2",
                "A",
                "A",
                "0"
              ],
              [
                "2",
                "B",
                "A",
                "0"
              ],
              [
                "2",
                "C",
                "A",
                "0"
              ],
              [
                "2",
                "D",
                "A",
                "0"
              ],
              [
                "3",
                "A",
                "A",
                "0"
              ],
              [
                "3",
                "B",
                "A",
                "0"
              ],
              [
                "3",
                "C",
                "A",
                "0"
              ],
              [
                "3",
                "D",
                "A",
                "0"
              ],
              [
                "4",
                "A",
                "A",
                "0"
              ],
              [
                "4",
                "B",
                "A",
                "0"
              ],
              [
                "4",
                "C",
                "A",
                "0"
              ],
              [
                "4",
                "D",
                "A",
                "1"
              ],
              [
                "5",
                "A",
                "A",
                "1"
              ],
              [
                "5",
                "B",
                "A",
                "0"
              ],
              [
                "5",
                "C",
                "A",
                "0"
              ],
              [
                "5",
                "D",
                "A",
                "0"
              ],
              [
                "6",
                "A",
                "A",
                "1"
              ],
              [
                "6",
                "B",
                "A",
                "0"
              ],
              [
                "6",
                "C",
                "A",
                "0"
              ],
              [
                "6",
                "D",
                "A",
                "1"
              ],
              [
                "7",
                "A",
                "A",
                "0"
              ],
              [
                "7",
                "B",
                "A",
                "0"
              ],
              [
                "7",
                "C",
                "A",
                "0"
              ],
              [
                "7",
                "D",
                "A",
                "1"
              ],
              [
                "8",
                "A",
                "A",
                "1"
              ],
              [
                "8",
                "B",
                "A",
                "0"
              ],
              [
                "8",
                "C",
                "A",
                "0"
              ],
              [
                "8",
                "D",
                "A",
                "1"
              ],
              [
                "9",
                "A",
                "A",
                "0"
              ],
              [
                "9",
                "B",
                "A",
                "0"
              ],
              [
                "9",
                "C",
                "A",
                "1"
              ],
              [
                "9",
                "D",
                "A",
                "0"
              ],
              [
                "10",
                "A",
                "A",
                "0"
              ],
              [
                "10",
                "B",
                "A",
                "0"
              ],
              [
                "10",
                "C",
                "A",
                "0"
              ],
              [
                "10",
                "D",
                "A",
                "0"
              ],
              [
                "11",
                "A",
                "A",
                "0"
              ],
              [
                "11",
                "B",
                "A",
                "0"
              ],
              [
                "11",
                "C",
                "A",
                "0"
              ],
              [
                "11",
                "D",
                "A",
                "0"
              ],
              [
                "12",
                "A",
                "A",
                "0"
              ],
              [
                "12",
                "B",
                "A",
                "0"
              ],
              [
                "12",
                "C",
                "A",
                "0"
              ],
              [
                "12",
                "D",
                "A",
                "0"
              ],
              [
                "13",
                "B",
                "A",
                "1"
              ],
              [
                "13",
                "C",
                "A",
                "0"
              ],
              [
                "13",
                "D",
                "A",
                "1"
              ]
            ]
          }
        ]
      }
    }
  }
}
                </code>
            </pre>
    </div>
    <div class="tab-pane fade" id="resTrainSeat2" role="tabpanel">
            <pre class="code-toolbar" style="height: 500px;">
                <code class="language-markup">

-------------------- RESPONSE GAGAL clinet_id salah -------------------
{
    "status": {
        "code": 400,
        "confirm": "failed",
        "message": [
            "Anda tidak terdaftar",
            "clinet_id tidak ditemukan"
        ]
    }
}
------- RESPONSE GAGAL transaction_id salah / tidak ditemukan ----------
{
  "status": {
    "code": 400,
    "confirm": "failed",
    "message": [
      "transaction_id tidak ditemukan"
    ]
  }
}
                </code>
            </pre>
    </div>
    <div class="tab-pane fade" id="resTrainSeat3" role="tabpanel">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Parameter</th>
                <th>Keterangan</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>code</th>
                <td>Kode status response</td>
            </tr>
            <tr>
                <th>confirm</th>
                <td>konfirmasi status response</td>
            </tr>
            <tr>
                <th>message</th>
                <td>Pesan response</td>
            </tr>
            <tr>
                <th>access_token</th>
                <td>Token yang di gunakan untuk request ketika login</td>
            </tr>
            <tr>
                <th>token_type</th>
                <td>Tipe token</td>
            </tr>

            <tr>
                <th>expires_in</th>
                <td>Masa berlaku token (detik)</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
